import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { NavBar } from "@/components/ui/navbar";
import { FloatPanelProvider } from "@/components/context/FloatPanelProvider";
import { CurrentChatProvider } from "@/components/context/CurrentChatProvider";
import { ManageProvider } from "@/components/context/ManageProvider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="h-full pt-20">
        <ManageProvider>
          <FloatPanelProvider>
            <CurrentChatProvider>{children}</CurrentChatProvider>
            <NavBar />
          </FloatPanelProvider>
        </ManageProvider>
      </body>
    </html>
  );
}
